[project]
name = "code-repair"
version = "0.0.1"
readme = "README.md"

dependencies = [
  "annotated-types>=0.6.0",
  "openai>=1.12.0",
  "pydantic>=2.6.1",
  "pydantic_core>=2.16.2",
  "typing_extensions>=4.9.0",

]

[tool.pyright]
pythonVersion = "3.10"
include = [
  "src/"
]
